name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "feature/*"

env:
  MONGO_URI: mongodb+srv://${{vars.MONGO_USER}}:${{secrets.MONGO_PASSWORD}}@cluster0.jv3yw.mongodb.net/solar?retryWrites=true&w=majority&appName=Cluster0

jobs:
  unit-testing:
    name: Unit Testing
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18, 20]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS Version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Unit Testing
        run: npm test

      - name: Archive Test Result
        uses: actions/upload-artifact@v3
        with:
          name: Mocha-Test-Result
          path: test-results.xml
